### ISSUE TITLE
SSCAN tomoscan vertical causes Writer error

### ISSUE THREAD

**Issue by userbeats** [SESAME-Synchrotron/BEATS_tomoscan#18] opened 2023-09-20 16:38 UTC
![image](https://github.com/SESAME-Synchrotron/BEATS_tomoscan/assets/133559532/68271c00-ab32-4d41-a181-cb5a0c96db5d)

**Comment by userbeats** [comment] 2023-09-20 16:39
@Mustafa-zubi

**Comment by Mustafa-zubi** [comment] 2023-09-20 20:04
@AbdallaDalleh @anas-abbadi 

we kindly need your help to investigate this issue ... the write keeps showing disconnecting PVs in which they are not disconnected ... as you can see some PVs case writer crash

also I'm attaching another screenshot shows disconnected PVs at different stage. 
<img width="1030" alt="Screenshot 2023-09-20 at 10 56 53 PM" src="https://github.com/SESAME-Synchrotron/BEATS_tomoscan/assets/10595891/082948bf-f948-4e42-975b-78fb5536a495">

**Comment by AbdallaDalleh** [comment] 2023-10-10 10:31
Hi @Mustafa-zubi , Is this the same issue that we worked on?

**Comment by Mustafa-zubi** [comment] 2023-10-10 10:48
@AbdallaDalleh  Yes, it is. I conclude that it is not an EPICS issue -- being wrong possibility is there :) -- I noticed that when the writer is heavily writing data this appears ... However, very soon I will have a meeting with technical people;e at APS I will ask if any had such issue

**Comment by gianthk** [comment] 2023-10-24 08:53
this is a GPFS accessibility issue and is being investigated by @ifoudeh and @Salman-matalgah

**Comment by gianthk** [comment] 2024-01-23 15:30
@ifoudeh @Salman-matalgah @Mustafa-zubi please close this issue if the problem is solved after discussion with IBM

**Comment by gianthk** [comment] 2024-02-13 13:37
not reproduced anymore

**Closed** 2024-02-13 13:36 UTC
